version: '3.6'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - PROXY_REALM=${PROXY_REALM}
      - HTTP_BASIC_USER=${HTTP_BASIC_USER}
      - HTTP_BASIC_PASS=${HTTP_BASIC_PASS}
  backend:
    image: nginxdemos/hello
    ports:
      - "80:80"
