version: '3.6'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "${PROXY_PORT:-80}:80"
    volumes:
      - ./default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
