version: '3.6'

services:
  nginx:
    image: nginxproxy/nginx-proxy
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - BACKEND_PORT=${BACKEND_PORT:-80}
      - PROXY_REALM=${PROXY_REALM}
      - HTTP_BASIC_USER=${HTTP_BASIC_USER}
      - HTTP_BASIC_PASS=${HTTP_BASIC_PASS}

  acme:
    image: nginxproxy/acme-companion
    container_name: acme
    environment:
      - NGINX_PROXY_CONTAINER=nginx
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx
    networks:
      - local
      - web

  backend:
    image: nginxdemos/hello
    ports:
      - "3000:80"
    environment:
      - VIRTUAL_HOST=${PULLPREVIEW_PUBLIC_DNS}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${PULLPREVIEW_PUBLIC_DNS}
