name: preview
on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || github.event.label.name == 'preview' || contains(github.event.pull_request.labels.*.name, 'preview')
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_PROXY_REALM: "nginx proxy"
          envkey_NGINX_HOST: "previews.sofatutor.com"
          envkey_BACKEND_PORT: "80"
          envkey_HTTP_BASIC_USER: "${{ secrets.HTTP_BASIC_USER }}"
          envkey_HTTP_BASIC_PASS: "${{ secrets.HTTP_BASIC_PASS }}"
      - uses: pullpreview/action@v5
        with:
          admins: mfittko
          always_on: main
          app_path: .
          instance_type: nano_2_0
          dns: previews.sofatutor.com
          registries: docker://index.docker.io/v1
          compose_files: docker-compose-preview.yml
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
